# Generated by Django 6.0.3 on 2026-03-22 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng Lab')),
                ('capacity', models.IntegerField(verbose_name='Sức chứa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả thiết bị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Phòng Lab',
                'verbose_name_plural': 'Danh sách phòng Lab',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELLED', 'Hủy')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('purpose', models.TextField(verbose_name='Mục đích sử dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.labroom')),
            ],
            options={
                'verbose_name': 'Lịch đặt phòng',
                'verbose_name_plural': 'Danh sách lịch đặt',
            },
        ),
    ]
